# Build APKs for Kiwi Browser
name: rclone_sftp_test

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  workflow_dispatch:
    inputs:
      prepareRelease:
        description: 'Create a draft release in Google Play Store'     
        required: true
        default: 'no'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [x64]

    # The GitHub Actions machines have a "slow disk", and a SSD "fast" disk.
    # However, there is not enough space to do all the processing on the SSD.
    
    # We refer to the disks based on their name in /dev/disk
    # /dev/disk/azure/root-part1 is / ("slow disk")
    # /dev/disk/azure/resource-part1 is a 14 GB ephemeral SSD disk mounted in /mnt

    # We store the source-code repository (kiwibrowser/src) on /dev/disk/azure/root-part1
    # We store cache, dependencies and output on /dev/disk/azure/resource-part1 (SSD)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Initializing build
        run: echo Initializing build for platform ${{ matrix.platform }}

      - name: Installing rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Creating rclone config
        run: |
          mkdir -p $HOME/.config/rclone/
          echo '[cache]' > $HOME/.config/rclone/rclone.conf
          echo 'type = sftp' >> $HOME/.config/rclone/rclone.conf
          echo 'host = ${{ secrets.SFTP_HOST }}' >> $HOME/.config/rclone/rclone.conf
          echo 'user = sftp' >> $HOME/.config/rclone/rclone.conf
          echo 'pass = ${{ secrets.SFTP_PASSWORD }}' >> $HOME/.config/rclone/rclone.conf

      - name: Downloading binary objects cache to $HOME/cache
        run: rclone copy --fast-list --transfers=128 cache:kiwibrowser-ccache-${{ matrix.platform }} $HOME/

      - name: Creating rclone config to upload the cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        run: |
          echo '[sync]' > $HOME/.config/rclone/rclone.conf
          echo 'type = sftp' >> $HOME/.config/rclone/rclone.conf
          echo 'host = ${{ secrets.SFTP_HOST }}' >> $HOME/.config/rclone/rclone.conf
          echo 'user = sftp' >> $HOME/.config/rclone/rclone.conf
          echo 'pass = ${{ secrets.SFTP_PASSWORD }}' >> $HOME/.config/rclone/rclone.conf

      - name: Uploading binary objects to cache
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        run: |
          echo "sfsf" > $HOME/github.file
          rclone copy --fast-list --transfers=32 $HOME/ sync:kiwibrowser-ccache-${{ matrix.platform }}/
