# Build APKs for Kiwi Browser
name: build apk

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  workflow_dispatch:
    inputs:
      prepareRelease:
        description: 'Create a draft release in Google Play Store'     
        required: true
        default: 'no'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [x64]

    # The GitHub Actions machines have a "slow disk", and a SSD "fast" disk.
    # However, there is not enough space to do all the processing on the SSD.
    
    # We refer to the disks based on their name in /dev/disk
    # /dev/disk/azure/root-part1 is / ("slow disk")
    # /dev/disk/azure/resource-part1 is a 14 GB ephemeral SSD disk mounted in /mnt

    # We store the source-code repository (kiwibrowser/src) on /dev/disk/azure/root-part1
    # We store cache, dependencies and output on /dev/disk/azure/resource-part1 (SSD)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Initializing build
        run: echo Initializing build for platform ${{ matrix.platform }}

      - name: Reclaiming disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo swapoff -a
          sudo rm -f /mnt/swapfile

      - name: Checking-out source-code in $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Creating secondary disk folder on /dev/disk/azure/resource-part1 (SSD)
        run: |
          sudo mkdir -p /extended_data
          sudo chown -R runner:docker /extended_data
      
      # If you want to use only the SSD, you can use:
      - name: On SSD - Creating symlink on /dev/disk/azure/root-part1 pointing to /dev/disk/azure/resource-part1
        run: |
          sudo ln -s /extended_data /mnt/secondary_disk
          sudo ln -s /mnt/secondary_disk $GITHUB_WORKSPACE/

      # or alternatively, to work on the main partition
      # - name: On HDD - Creating symlink on /dev/disk/azure/root-part1 pointing to /dev/disk/azure/resource-part1
      #  run: |
      #    sudo ln -s /extended_data /mnt/secondary_disk
      #    sudo ln -s /mnt/secondary_disk $GITHUB_WORKSPACE/

      # We cannot checkout outside of $GITHUB_WORKSPACE, but we want to checkout to the SSD
      # so we have a symbolic link $GITHUB_WORKSPACE/secondary_disk/ pointing to the SSD
      # and checkout the code there
      - name: Checking-out CIPD dependencies in /mnt/secondary_disk/.cipd
        uses: actions/checkout@v2
        with:
          repository: kiwibrowser/dependencies
          path: ./secondary_disk/.cipd 

      - name: Linking .cipd in the proper path and copying .gclient and .gclient_entries
        run: |
          ln -s $GITHUB_WORKSPACE/./secondary_disk/.cipd ..
          cp ../.cipd/.gclient ..
          cp ../.cipd/.gclient_entries ..

      - name: Installing rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Updating APT repository
        run: sudo apt-get update

      - name: Installing Python and OpenJDK
        run: sudo apt-get install -y python libncurses5 ccache

     # - name: Setting-up Java 8 as default Java provider
    #    run: sudo update-java-alternatives --set java-1.8.0-openjdk-amd64

      - name: Installing system dependencies
        run: |
          sudo bash install-build-deps.sh --no-chromeos-fonts --no-arm --no-nacl --no-backwards-compatible
          build/linux/sysroot_scripts/install-sysroot.py --arch=amd64

      - name: Creating output folder
        run: mkdir -p secondary_disk/out/android_${{ matrix.platform }}

      #- name: Generating one-time APK signature key
      #  run: keytool -genkey -v -keystore keystore.jks -alias dev -keyalg RSA -keysize 2048 -validity 10000 -storepass public_password -keypass public_password -dname "cn=Kiwi Browser (unverified), ou=Actions, o=Kiwi Browser, c=GitHub"

      - name: Copying args.gn to target folder
        run: cat .build/android_arm/args.gn | sed "s#target_cpu = \"arm\"#target_cpu = \"${{ matrix.platform }}\"#" | sed "s#android_default_version_name = \"Git\"#android_default_version_name = \"Git$(date '+%y%m%d')Gen${{ github.run_id }}\"#" > secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Modifying args.gn (arm)
        if: matrix.platform == 'arm'
        run: sed -i "s#android_default_version_code = \"1\"#android_default_version_code = \"$(date '+%y%m%d')1\"#" secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Modifying args.gn (arm64)
        if: matrix.platform == 'arm64'
        run: sed -i "s#android_default_version_code = \"1\"#android_default_version_code = \"$(date '+%y%m%d')2\"#" secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Modifying args.gn (x86)
        if: matrix.platform == 'x86'
        run: sed -i "s#android_default_version_code = \"1\"#android_default_version_code = \"$(date '+%y%m%d')3\"#" secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Modifying args.gn (x64)
        if: matrix.platform == 'x64'
        run: sed -i "s#android_default_version_code = \"1\"#android_default_version_code = \"$(date '+%y%m%d')4\"#" secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Displaying args.gn
        run: cat secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Downloading depot_tools
        working-directory: ./secondary_disk
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Adding depot_tools to path
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo "::add-path::$GITHUB_WORKSPACE/secondary_disk/depot_tools"

      - name: Setting environment variables
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          echo "::set-env name=CC::ccache clang -Qunused-arguments"
          echo "::set-env name=CXX::ccache clang++ -Qunused-arguments"

      - name: Checking available disk-space
        run: df -h

      - name: Creating rclone config
        run: |
          mkdir -p $HOME/.config/rclone/
          echo '[cache]' > $HOME/.config/rclone/rclone.conf
          echo 'type = sftp' >> $HOME/.config/rclone/rclone.conf
          echo 'host = ${{ secrets.SFTP_HOST }}' >> $HOME/.config/rclone/rclone.conf
          echo 'user = sftp' >> $HOME/.config/rclone/rclone.conf
          echo 'pass = ${{ secrets.SFTP_PASSWORD }}' >> $HOME/.config/rclone/rclone.conf

      - name: Creating cache folder on /dev/disk/azure/resource-part1 (SSD)
        run: |
          sudo mkdir -p /mnt/cache
          sudo chown -R runner:docker /mnt/cache
          
      - name: Creating symlink in $HOME/cache pointing to cache on /dev/disk/azure/resource-part1
        run: ln -s /mnt/cache $HOME/

      - name: Downloading binary objects cache to $HOME/cache
        run: rclone copy --fast-list --transfers=128 cache:kiwibrowser-ccache-${{ matrix.platform }} $HOME/cache

      - name: Checking available disk-space after downloading cache
        run: df -h
        
      # - name: Fetching number for the latest stable version of Chromium
      #  run: curl "https://omahaproxy.appspot.com/all" | grep -Fi "android,stable" | cut -f3 -d"," | awk '{split($0,a,"."); print "MAJOR=" a[1] "\nMINOR=" a[2] "\nBUILD=" a[3] "\nPATCH=" a[4]}' > chrome/VERSION
        
      - name: Calculating cache size
        run: du -csh $HOME/cache

      - name: Creating ccache configuration
        run: |
          mkdir -p $HOME/.ccache/
          echo 'compiler_check = none' >> $HOME/.ccache/ccache.conf
          echo "stats = false" >> $HOME/.ccache/ccache.conf
          echo 'max_size = 20G' >> $HOME/.ccache/ccache.conf
          echo "base_dir = $HOME" >> $HOME/.ccache/ccache.conf
          echo "cache_dir = $HOME/cache" >> $HOME/.ccache/ccache.conf
          echo "hash_dir = false" >> $HOME/.ccache/ccache.conf

      - name: Running gclient runhooks
        run: gclient runhooks

      - name: Generating build files
        run: gn gen ./secondary_disk/out/android_${{ matrix.platform }}

      - name: Checking available disk-space before build cache
        run: df -h

      - name: Creating rclone config to upload the cache
        run: |
          echo '[sync]' > $HOME/.config/rclone/rclone.conf
          echo 'type = sftp' >> $HOME/.config/rclone/rclone.conf
          echo 'host = ${{ secrets.SFTP_HOST }}' >> $HOME/.config/rclone/rclone.conf
          echo 'user = sftp' >> $HOME/.config/rclone/rclone.conf
          echo 'pass = ${{ secrets.SFTP_PASSWORD }}' >> $HOME/.config/rclone/rclone.conf

      - name: Checking available disk-space before build
        run: df -h

      # We compile component by component as 6 hours is not enough for the initial build
      # so we can snapshot between each component and continue further from the snapshot
      - name: Compiling source-code (base)
        run: ninja -C ./secondary_disk/out/android_${{ matrix.platform }} base

      - name: Uploading binary objects to cache
        run: rclone copy --fast-list --transfers=32 $HOME/cache/ sync:kiwibrowser-ccache-${{ matrix.platform }}/
